import AppKit
import Foundation

/// 剪贴板历史:文本 / 文件 / 图片,支持置顶与搜索。
/// 默认只保存在内存;开启"保存到磁盘"后文本和文件记录写入 Application Support(图片始终只在内存)
@Observable
@MainActor
final class ClipboardStore {
    struct Item: Identifiable, Equatable, Codable {
        enum Content: Equatable, Codable {
            case text(String)
            case files([String])
            case image(Data)
        }

        var id = UUID()
        let content: Content
        var time: Date
        var pinned = false

        var isImage: Bool {
            if case .image = content { return true }
            return false
        }

        /// 列表展示与搜索用的文字
        var title: String {
            switch content {
            case .text(let text):
                return text.trimmingCharacters(in: .whitespacesAndNewlines)
            case .files(let paths):
                return paths.map { ($0 as NSString).lastPathComponent }.joined(separator: "、")
            case .image:
                return "图片"
            }
        }

        var symbolName: String {
            switch content {
            case .text: return "doc.on.clipboard"
            case .files(let paths): return paths.count > 1 ? "doc.on.doc" : "doc"
            case .image: return "photo"
            }
        }

        func matches(_ query: String) -> Bool {
            guard !query.isEmpty else { return true }
            if case .files(let paths) = content {
                return paths.contains { $0.localizedCaseInsensitiveContains(query) }
            }
            return title.localizedCaseInsensitiveContains(query)
        }
    }

    static let persistKey = "clipboardPersist"
    /// 未置顶条目的上限;置顶条目不计入、不会被挤掉
    static let limit = 100
    /// 超过此大小的图片不记录,避免占用过多内存
    static let maxImageBytes = 20 * 1024 * 1024

    /// 密码管理器等会用这些类型标记敏感/临时内容(nspasteboard.org 约定),不记录
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
    ]

    private(set) var items: [Item] = []

    var persist: Bool = UserDefaults.standard.bool(forKey: ClipboardStore.persistKey) {
        didSet {
            UserDefaults.standard.set(persist, forKey: Self.persistKey)
            if persist { save() } else { try? FileManager.default.removeItem(at: storeURL) }
        }
    }

    /// 置顶在前,其余按时间倒序
    var sortedItems: [Item] {
        items.filter(\.pinned) + items.filter { !$0.pinned }
    }

    func filtered(_ query: String) -> [Item] {
        let query = query.trimmingCharacters(in: .whitespaces)
        return sortedItems.filter { $0.matches(query) }
    }

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount = 0
    private var task: Task<Void, Never>?
    private var saveTask: Task<Void, Never>?
    private let storeURL: URL
    @ObservationIgnored private var thumbnails: [UUID: NSImage] = [:]

    init(storeURL: URL? = nil) {
        self.storeURL = storeURL ?? FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("MacTool", isDirectory: true)
            .appendingPathComponent("clipboard.json")
    }

    func start() {
        guard task == nil else { return }
        if persist { load() }
        lastChangeCount = pasteboard.changeCount
        task = Task { [weak self] in
            while !Task.isCancelled {
                self?.poll()
                try? await Task.sleep(for: .milliseconds(500))
            }
        }
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.ignoredTypes), let content = Self.readContent(pasteboard) else { return }
        add(content)
    }

    /// 优先级:文件 > 文本 > 图片(访达复制文件时也会附带文件名文本和图标图片)
    private static func readContent(_ pasteboard: NSPasteboard) -> Item.Content? {
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls.map(\.path))
        }
        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return .text(text)
        }
        if let png = pasteboard.data(forType: .png) {
            return png.count <= maxImageBytes ? .image(png) : nil
        }
        // TIFF(截图等)体积大,转成 PNG 再存
        if let tiff = pasteboard.data(forType: .tiff), tiff.count <= maxImageBytes * 4,
           let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]),
           png.count <= maxImageBytes {
            return .image(png)
        }
        return nil
    }

    func add(_ content: Item.Content, time: Date = .now) {
        // 重复内容提到最前,保留置顶状态
        var item = Item(content: content, time: time)
        if let index = items.firstIndex(where: { $0.content == content }) {
            item = items.remove(at: index)
            item.time = time
        }
        items.insert(item, at: 0)
        trim()
        scheduleSave()
    }

    private func trim() {
        var unpinned = 0
        items.removeAll { item in
            guard !item.pinned else { return false }
            unpinned += 1
            if unpinned > Self.limit {
                thumbnails[item.id] = nil
                return true
            }
            return false
        }
    }

    func copyBack(_ item: Item) {
        pasteboard.clearContents()
        switch item.content {
        case .text(let text):
            pasteboard.setString(text, forType: .string)
        case .files(let paths):
            pasteboard.writeObjects(paths.map { URL(fileURLWithPath: $0) as NSURL })
        case .image(let data):
            pasteboard.setData(data, forType: .png)
            if let tiff = NSImage(data: data)?.tiffRepresentation {
                pasteboard.setData(tiff, forType: .tiff)
            }
        }
        lastChangeCount = pasteboard.changeCount
        add(item.content)
    }

    func togglePin(_ item: Item) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        trim()
        scheduleSave()
    }

    func remove(_ item: Item) {
        items.removeAll { $0.id == item.id }
        thumbnails[item.id] = nil
        scheduleSave()
    }

    /// 只清空未置顶的记录
    func clear() {
        items.removeAll { !$0.pinned }
        thumbnails = thumbnails.filter { id, _ in items.contains { $0.id == id } }
        scheduleSave()
    }

    func thumbnail(for item: Item) -> NSImage? {
        guard case .image(let data) = item.content else { return nil }
        if let cached = thumbnails[item.id] { return cached }
        let image = NSImage(data: data)
        thumbnails[item.id] = image
        return image
    }

    // MARK: - 持久化

    private func scheduleSave() {
        guard persist else { return }
        saveTask?.cancel()
        saveTask = Task { [weak self] in
            try? await Task.sleep(for: .seconds(1))
            guard !Task.isCancelled else { return }
            self?.save()
        }
    }

    private func save() {
        let persisted = items.filter { !$0.isImage }
        do {
            try FileManager.default.createDirectory(at: storeURL.deletingLastPathComponent(), withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(persisted).write(to: storeURL, options: .atomic)
            // 剪贴板可能含敏感内容,仅本人可读
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: storeURL.path)
        } catch {
            NSLog("MacTool: 保存剪贴板历史失败 \(error)")
        }
    }

    private func load() {
        guard let data = try? Data(contentsOf: storeURL),
              let saved = try? JSONDecoder().decode([Item].self, from: data) else { return }
        items = saved
        trim()
    }
}
